# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OB1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OB1
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  target 'OB1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OB1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

