
export const countryList = [
  {"name":"Afghanistan","cca2":"AF","countryCode":"004"},
  {"name":"Åland Islands","cca2":"AX","countryCode":"248"},
  {"name":"Albania","cca2":"AL","countryCode":"008"},
  {"name":"Algeria","cca2":"DZ","countryCode":"012"},
  {"name":"American Samoa","cca2":"AS","countryCode":"016"},
  {"name":"Andorra","cca2":"AD","countryCode":"020"},
  {"name":"Angola","cca2":"AO","countryCode":"024"},
  {"name":"Anguilla","cca2":"AI","countryCode":"660"},
  {"name":"Antarctica","cca2":"AQ","countryCode":"010"},
  {"name":"Antigua and Barbuda","cca2":"AG","countryCode":"028"},
  {"name":"Argentina","cca2":"AR","countryCode":"032"},
  {"name":"Armenia","cca2":"AM","countryCode":"051"},
  {"name":"Aruba","cca2":"AW","countryCode":"533"},
  {"name":"Australia","cca2":"AU","countryCode":"036"},
  {"name":"Austria","cca2":"AT","countryCode":"040"},
  {"name":"Azerbaijan","cca2":"AZ","countryCode":"031"},
  {"name":"Bahamas","cca2":"BS","countryCode":"044"},
  {"name":"Bahrain","cca2":"BH","countryCode":"048"},
  {"name":"Bangladesh","cca2":"BD","countryCode":"050"},
  {"name":"Barbados","cca2":"BB","countryCode":"052"},
  {"name":"Belarus","cca2":"BY","countryCode":"112"},
  {"name":"Belgium","cca2":"BE","countryCode":"056"},
  {"name":"Belize","cca2":"BZ","countryCode":"084"},
  {"name":"Benin","cca2":"BJ","countryCode":"204"},
  {"name":"Bermuda","cca2":"BM","countryCode":"060"},
  {"name":"Bhutan","cca2":"BT","countryCode":"064"},
  {"name":"Bolivia (Plurinational State of)","cca2":"BO","countryCode":"068"},
  {"name":"Bonaire, Sint Eustatius and Saba","cca2":"BQ","countryCode":"535"},
  {"name":"Bosnia and Herzegovina","cca2":"BA","countryCode":"070"},
  {"name":"Botswana","cca2":"BW","countryCode":"072"},
  {"name":"Bouvet Island","cca2":"BV","countryCode":"074"},
  {"name":"Brazil","cca2":"BR","countryCode":"076"},
  {"name":"British Indian Ocean Territory","cca2":"IO","countryCode":"086"},
  {"name":"Brunei Darussalam","cca2":"BN","countryCode":"096"},
  {"name":"Bulgaria","cca2":"BG","countryCode":"100"},
  {"name":"Burkina Faso","cca2":"BF","countryCode":"854"},
  {"name":"Burundi","cca2":"BI","countryCode":"108"},
  {"name":"Cambodia","cca2":"KH","countryCode":"116"},
  {"name":"Cameroon","cca2":"CM","countryCode":"120"},
  {"name":"Canada","cca2":"CA","countryCode":"124"},
  {"name":"Cabo Verde","cca2":"CV","countryCode":"132"},
  {"name":"Cayman Islands","cca2":"KY","countryCode":"136"},
  {"name":"Central African Republic","cca2":"CF","countryCode":"140"},
  {"name":"Chad","cca2":"TD","countryCode":"148"},
  {"name":"Chile","cca2":"CL","countryCode":"152"},
  {"name":"China","cca2":"CN","countryCode":"156"},
  {"name":"Christmas Island","cca2":"CX","countryCode":"162"},
  {"name":"Cocos (Keeling) Islands","cca2":"CC","countryCode":"166"},
  {"name":"Colombia","cca2":"CO","countryCode":"170"},
  {"name":"Comoros","cca2":"KM","countryCode":"174"},
  {"name":"Congo","cca2":"CG","countryCode":"178"},
  {"name":"Congo (Democratic Republic of the)","cca2":"CD","countryCode":"180"},
  {"name":"Cook Islands","cca2":"CK","countryCode":"184"},
  {"name":"Costa Rica","cca2":"CR","countryCode":"188"},
  {"name":"Côte d'Ivoire","cca2":"CI","countryCode":"384"},
  {"name":"Croatia","cca2":"HR","countryCode":"191"},
  {"name":"Cuba","cca2":"CU","countryCode":"192"},
  {"name":"Curaçao","cca2":"CW","countryCode":"531"},
  {"name":"Cyprus","cca2":"CY","countryCode":"196"},
  {"name":"Czech Republic","cca2":"CZ","countryCode":"203"},
  {"name":"Denmark","cca2":"DK","countryCode":"208"},
  {"name":"Djibouti","cca2":"DJ","countryCode":"262"},
  {"name":"Dominica","cca2":"DM","countryCode":"212"},
  {"name":"Dominican Republic","cca2":"DO","countryCode":"214"},
  {"name":"Ecuador","cca2":"EC","countryCode":"218"},
  {"name":"Egypt","cca2":"EG","countryCode":"818"},
  {"name":"El Salvador","cca2":"SV","countryCode":"222"},
  {"name":"Equatorial Guinea","cca2":"GQ","countryCode":"226"},
  {"name":"Eritrea","cca2":"ER","countryCode":"232"},
  {"name":"Estonia","cca2":"EE","countryCode":"233"},
  {"name":"Ethiopia","cca2":"ET","countryCode":"231"},
  {"name":"Falkland Islands (Malvinas)","cca2":"FK","countryCode":"238"},
  {"name":"Faroe Islands","cca2":"FO","countryCode":"234"},
  {"name":"Fiji","cca2":"FJ","countryCode":"242"},
  {"name":"Finland","cca2":"FI","countryCode":"246"},
  {"name":"France","cca2":"FR","countryCode":"250"},
  {"name":"French Guiana","cca2":"GF","countryCode":"254"},
  {"name":"French Polynesia","cca2":"PF","countryCode":"258"},
  {"name":"French Southern Territories","cca2":"TF","countryCode":"260"},
  {"name":"Gabon","cca2":"GA","countryCode":"266"},
  {"name":"Gambia","cca2":"GM","countryCode":"270"},
  {"name":"Georgia","cca2":"GE","countryCode":"268"},
  {"name":"Germany","cca2":"DE","countryCode":"276"},
  {"name":"Ghana","cca2":"GH","countryCode":"288"},
  {"name":"Gibraltar","cca2":"GI","countryCode":"292"},
  {"name":"Greece","cca2":"GR","countryCode":"300"},
  {"name":"Greenland","cca2":"GL","countryCode":"304"},
  {"name":"Grenada","cca2":"GD","countryCode":"308"},
  {"name":"Guadeloupe","cca2":"GP","countryCode":"312"},
  {"name":"Guam","cca2":"GU","countryCode":"316"},
  {"name":"Guatemala","cca2":"GT","countryCode":"320"},
  {"name":"Guernsey","cca2":"GG","countryCode":"831"},
  {"name":"Guinea","cca2":"GN","countryCode":"324"},
  {"name":"Guinea-Bissau","cca2":"GW","countryCode":"624"},
  {"name":"Guyana","cca2":"GY","countryCode":"328"},
  {"name":"Haiti","cca2":"HT","countryCode":"332"},
  {"name":"Heard Island and McDonald Islands","cca2":"HM","countryCode":"334"},
  {"name":"Holy See","cca2":"VA","countryCode":"336"},
  {"name":"Honduras","cca2":"HN","countryCode":"340"},
  {"name":"Hong Kong","cca2":"HK","countryCode":"344"},
  {"name":"Hungary","cca2":"HU","countryCode":"348"},
  {"name":"Iceland","cca2":"IS","countryCode":"352"},
  {"name":"India","cca2":"IN","countryCode":"356"},
  {"name":"Indonesia","cca2":"ID","countryCode":"360"},
  {"name":"Iran (Islamic Republic of)","cca2":"IR","countryCode":"364"},
  {"name":"Iraq","cca2":"IQ","countryCode":"368"},
  {"name":"Ireland","cca2":"IE","countryCode":"372"},
  {"name":"Isle of Man","cca2":"IM","countryCode":"833"},
  {"name":"Israel","cca2":"IL","countryCode":"376"},
  {"name":"Italy","cca2":"IT","countryCode":"380"},
  {"name":"Jamaica","cca2":"JM","countryCode":"388"},
  {"name":"Japan","cca2":"JP","countryCode":"392"},
  {"name":"Jersey","cca2":"JE","countryCode":"832"},
  {"name":"Jordan","cca2":"JO","countryCode":"400"},
  {"name":"Kazakhstan","cca2":"KZ","countryCode":"398"},
  {"name":"Kenya","cca2":"KE","countryCode":"404"},
  {"name":"Kiribati","cca2":"KI","countryCode":"296"},
  {"name":"Korea (Democratic People's Republic of)","cca2":"KP","countryCode":"408"},
  {"name":"Korea (Republic of)","cca2":"KR","countryCode":"410"},
  {"name":"Kuwait","cca2":"KW","countryCode":"414"},
  {"name":"Kyrgyzstan","cca2":"KG","countryCode":"417"},
  {"name":"Lao People's Democratic Republic","cca2":"LA","countryCode":"418"},
  {"name":"Latvia","cca2":"LV","countryCode":"428"},
  {"name":"Lebanon","cca2":"LB","countryCode":"422"},
  {"name":"Lesotho","cca2":"LS","countryCode":"426"},
  {"name":"Liberia","cca2":"LR","countryCode":"430"},
  {"name":"Libya","cca2":"LY","countryCode":"434"},
  {"name":"Liechtenstein","cca2":"LI","countryCode":"438"},
  {"name":"Lithuania","cca2":"LT","countryCode":"440"},
  {"name":"Luxembourg","cca2":"LU","countryCode":"442"},
  {"name":"Macao","cca2":"MO","countryCode":"446"},
  {"name":"Macedonia (the former Yugoslav Republic of)","cca2":"MK","countryCode":"807"},
  {"name":"Madagascar","cca2":"MG","countryCode":"450"},
  {"name":"Malawi","cca2":"MW","countryCode":"454"},
  {"name":"Malaysia","cca2":"MY","countryCode":"458"},
  {"name":"Maldives","cca2":"MV","countryCode":"462"},
  {"name":"Mali","cca2":"ML","countryCode":"466"},
  {"name":"Malta","cca2":"MT","countryCode":"470"},
  {"name":"Marshall Islands","cca2":"MH","countryCode":"584"},
  {"name":"Martinique","cca2":"MQ","countryCode":"474"},
  {"name":"Mauritania","cca2":"MR","countryCode":"478"},
  {"name":"Mauritius","cca2":"MU","countryCode":"480"},
  {"name":"Mayotte","cca2":"YT","countryCode":"175"},
  {"name":"Mexico","cca2":"MX","countryCode":"484"},
  {"name":"Micronesia (Federated States of)","cca2":"FM","countryCode":"583"},
  {"name":"Moldova (Republic of)","cca2":"MD","countryCode":"498"},
  {"name":"Monaco","cca2":"MC","countryCode":"492"},
  {"name":"Mongolia","cca2":"MN","countryCode":"496"},
  {"name":"Montenegro","cca2":"ME","countryCode":"499"},
  {"name":"Montserrat","cca2":"MS","countryCode":"500"},
  {"name":"Morocco","cca2":"MA","countryCode":"504"},
  {"name":"Mozambique","cca2":"MZ","countryCode":"508"},
  {"name":"Myanmar","cca2":"MM","countryCode":"104"},
  {"name":"Namibia","cca2":"NA","countryCode":"516"},
  {"name":"Nauru","cca2":"NR","countryCode":"520"},
  {"name":"Nepal","cca2":"NP","countryCode":"524"},
  {"name":"Netherlands","cca2":"NL","countryCode":"528"},
  {"name":"New Caledonia","cca2":"NC","countryCode":"540"},
  {"name":"New Zealand","cca2":"NZ","countryCode":"554"},
  {"name":"Nicaragua","cca2":"NI","countryCode":"558"},
  {"name":"Niger","cca2":"NE","countryCode":"562"},
  {"name":"Nigeria","cca2":"NG","countryCode":"566"},
  {"name":"Niue","cca2":"NU","countryCode":"570"},
  {"name":"Norfolk Island","cca2":"NF","countryCode":"574"},
  {"name":"Northern Mariana Islands","cca2":"MP","countryCode":"580"},
  {"name":"Norway","cca2":"NO","countryCode":"578"},
  {"name":"Oman","cca2":"OM","countryCode":"512"},
  {"name":"Pakistan","cca2":"PK","countryCode":"586"},
  {"name":"Palau","cca2":"PW","countryCode":"585"},
  {"name":"Palestine, State of","cca2":"PS","countryCode":"275"},
  {"name":"Panama","cca2":"PA","countryCode":"591"},
  {"name":"Papua New Guinea","cca2":"PG","countryCode":"598"},
  {"name":"Paraguay","cca2":"PY","countryCode":"600"},
  {"name":"Peru","cca2":"PE","countryCode":"604"},
  {"name":"Philippines","cca2":"PH","countryCode":"608"},
  {"name":"Pitcairn","cca2":"PN","countryCode":"612"},
  {"name":"Poland","cca2":"PL","countryCode":"616"},
  {"name":"Portugal","cca2":"PT","countryCode":"620"},
  {"name":"Puerto Rico","cca2":"PR","countryCode":"630"},
  {"name":"Qatar","cca2":"QA","countryCode":"634"},
  {"name":"Réunion","cca2":"RE","countryCode":"638"},
  {"name":"Romania","cca2":"RO","countryCode":"642"},
  {"name":"Russian Federation","cca2":"RU","countryCode":"643"},
  {"name":"Rwanda","cca2":"RW","countryCode":"646"},
  {"name":"Saint Barthélemy","cca2":"BL","countryCode":"652"},
  {"name":"Saint Helena, Ascension and Tristan da Cunha","cca2":"SH","countryCode":"654"},
  {"name":"Saint Kitts and Nevis","cca2":"KN","countryCode":"659"},
  {"name":"Saint Lucia","cca2":"LC","countryCode":"662"},
  {"name":"Saint Martin (French part)","cca2":"MF","countryCode":"663"},
  {"name":"Saint Pierre and Miquelon","cca2":"PM","countryCode":"666"},
  {"name":"Saint Vincent and the Grenadines","cca2":"VC","countryCode":"670"},
  {"name":"Samoa","cca2":"WS","countryCode":"882"},
  {"name":"San Marino","cca2":"SM","countryCode":"674"},
  {"name":"Sao Tome and Principe","cca2":"ST","countryCode":"678"},
  {"name":"Saudi Arabia","cca2":"SA","countryCode":"682"},
  {"name":"Senegal","cca2":"SN","countryCode":"686"},
  {"name":"Serbia","cca2":"RS","countryCode":"688"},
  {"name":"Seychelles","cca2":"SC","countryCode":"690"},
  {"name":"Sierra Leone","cca2":"SL","countryCode":"694"},
  {"name":"Singapore","cca2":"SG","countryCode":"702"},
  {"name":"Sint Maarten (Dutch part)","cca2":"SX","countryCode":"534"},
  {"name":"Slovakia","cca2":"SK","countryCode":"703"},
  {"name":"Slovenia","cca2":"SI","countryCode":"705"},
  {"name":"Solomon Islands","cca2":"SB","countryCode":"090"},
  {"name":"Somalia","cca2":"SO","countryCode":"706"},
  {"name":"South Africa","cca2":"ZA","countryCode":"710"},
  {"name":"South Georgia and the South Sandwich Islands","cca2":"GS","countryCode":"239"},
  {"name":"South Sudan","cca2":"SS","countryCode":"728"},
  {"name":"Spain","cca2":"ES","countryCode":"724"},
  {"name":"Sri Lanka","cca2":"LK","countryCode":"144"},
  {"name":"Sudan","cca2":"SD","countryCode":"729"},
  {"name":"Suriname","cca2":"SR","countryCode":"740"},
  {"name":"Svalbard and Jan Mayen","cca2":"SJ","countryCode":"744"},
  {"name":"Swaziland","cca2":"SZ","countryCode":"748"},
  {"name":"Sweden","cca2":"SE","countryCode":"752"},
  {"name":"Switzerland","cca2":"CH","countryCode":"756"},
  {"name":"Syrian Arab Republic","cca2":"SY","countryCode":"760"},
  {"name":"Taiwan, Province of China","cca2":"TW","countryCode":"158"},
  {"name":"Tajikistan","cca2":"TJ","countryCode":"762"},
  {"name":"Tanzania, United Republic of","cca2":"TZ","countryCode":"834"},
  {"name":"Thailand","cca2":"TH","countryCode":"764"},
  {"name":"Timor-Leste","cca2":"TL","countryCode":"626"},
  {"name":"Togo","cca2":"TG","countryCode":"768"},
  {"name":"Tokelau","cca2":"TK","countryCode":"772"},
  {"name":"Tonga","cca2":"TO","countryCode":"776"},
  {"name":"Trinidad and Tobago","cca2":"TT","countryCode":"780"},
  {"name":"Tunisia","cca2":"TN","countryCode":"788"},
  {"name":"Turkey","cca2":"TR","countryCode":"792"},
  {"name":"Turkmenistan","cca2":"TM","countryCode":"795"},
  {"name":"Turks and Caicos Islands","cca2":"TC","countryCode":"796"},
  {"name":"Tuvalu","cca2":"TV","countryCode":"798"},
  {"name":"Uganda","cca2":"UG","countryCode":"800"},
  {"name":"Ukraine","cca2":"UA","countryCode":"804"},
  {"name":"United Arab Emirates","cca2":"AE","countryCode":"784"},
  {"name":"United Kingdom of Great Britain and Northern Ireland","cca2":"GB","countryCode":"826"},
  {"name":"United States of America","cca2":"US","countryCode":"840"},
  {"name":"United States","cca2":"US","countryCode":"840"},
  {"name":"United States Minor Outlying Islands","cca2":"UM","countryCode":"581"},
  {"name":"Uruguay","cca2":"UY","countryCode":"858"},
  {"name":"Uzbekistan","cca2":"UZ","countryCode":"860"},
  {"name":"Vanuatu","cca2":"VU","countryCode":"548"},
  {"name":"Venezuela (Bolivarian Republic of)","cca2":"VE","countryCode":"862"},
  {"name":"Vietnam","cca2":"VN","countryCode":"704"},
  {"name":"Virgin Islands (British)","cca2":"VG","countryCode":"092"},
  {"name":"Virgin Islands (U.S.)","cca2":"VI","countryCode":"850"},
  {"name":"Wallis and Futuna","cca2":"WF","countryCode":"876"},
  {"name":"Western Sahara","cca2":"EH","countryCode":"732"},
  {"name":"Yemen","cca2":"YE","countryCode":"887"},
  {"name":"Zambia","cca2":"ZM","countryCode":"894"},
  {"name":"Zimbabwe","cca2":"ZW","countryCode":"716"}
]
